# Generated by Django 3.0.6 on 2020-06-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200606_1028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_login',
        ),
    ]
