# Generated by Django 3.0.6 on 2020-06-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200606_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
